[package]
name = "erased-cells-testkit"
version.workspace = true
edition.workspace = true
publish = false

[features]
default = []
gdal = ["dep:gdal" ]


[dependencies]
once_cell.workspace = true
gdal = { version = "0.16.0", optional = true }
